# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cs268225\Documents\Git\Analysis_GUI\UI\main_ui\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 801, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuAnalysis_GUI = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis_GUI.setObjectName("menuAnalysis_GUI")
        self.menuCalibration = QtWidgets.QMenu(self.menuAnalysis_GUI)
        self.menuCalibration.setObjectName("menuCalibration")
        self.menuSession = QtWidgets.QMenu(self.menuAnalysis_GUI)
        self.menuSession.setObjectName("menuSession")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionGenerate = QtWidgets.QAction(MainWindow)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionClose_2 = QtWidgets.QAction(MainWindow)
        self.actionClose_2.setObjectName("actionClose_2")
        self.actionErase = QtWidgets.QAction(MainWindow)
        self.actionErase.setObjectName("actionErase")
        self.menuCalibration.addAction(self.actionCreate)
        self.menuCalibration.addAction(self.actionGenerate)
        self.menuCalibration.addAction(self.actionSave_2)
        self.menuCalibration.addAction(self.actionErase)
        self.menuSession.addAction(self.actionNew)
        self.menuSession.addAction(self.actionLoad)
        self.menuSession.addAction(self.actionSave)
        self.menuSession.addAction(self.actionClose_2)
        self.menuAnalysis_GUI.addAction(self.menuSession.menuAction())
        self.menuAnalysis_GUI.addAction(self.menuCalibration.menuAction())
        self.menuAnalysis_GUI.addAction(self.actionClose)
        self.menubar.addAction(self.menuAnalysis_GUI.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.menuAnalysis_GUI.setTitle(_translate("MainWindow", "Analysis GUI"))
        self.menuCalibration.setTitle(_translate("MainWindow", "Calibration"))
        self.menuSession.setTitle(_translate("MainWindow", "Session"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionCreate.setText(_translate("MainWindow", "New..."))
        self.actionGenerate.setText(_translate("MainWindow", "Load..."))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionLoad.setText(_translate("MainWindow", "Load..."))
        self.actionClose.setText(_translate("MainWindow", "Close GUI"))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionSave_2.setText(_translate("MainWindow", "Save..."))
        self.actionClose_2.setText(_translate("MainWindow", "Close"))
        self.actionErase.setText(_translate("MainWindow", "Erase"))